import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Banner from "@/components/PageComponets/HomePage/Banner";
import Corousal from "@/components/PageComponets/HomePage/Corousal";
import Agents from "@/components/PageComponets/HomePage/Agents";
import Properties from "@/components/PageComponets/HomePage/Properties";
import GoogleBanner from "@/components/PageComponets/HomePage/GoogleBanner";
import { useDispatch } from "react-redux";
import {
  getAllProperty,
  getPropertyData,
  searchProperty
} from "@/stores/Property/propertyAction";
import { Box, Center, Spinner } from "@chakra-ui/react";
const settings = {
  dots: false,
  infinite: true,
  speed: 500,
  slidesToShow: 1,
  arrows: true,
  // slidesToScroll: 1
};

export default function Home() {
  const dispatch = useDispatch();
  const [properties, setProperties] = useState();
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    // getAllProperty(setProperties, setLoading);
    const data={
    dataOption: "all",
    searchCriteriaList: []
    }
    searchProperty(data,setProperties, setLoading);
  }, []);

  const handleChildSubmit = (searchData) => {

    const data = {
      dataOption: "all",
      searchCriteriaList: []
    };

    if (searchData.propetyType) {
      data.searchCriteriaList.push({
        filterKey: "propertyType",
        value: searchData.propetyType,
        operation: "eq"
      });
    }
      searchProperty(data,setProperties, setLoading);
};

  return (
    <>
      <Head>
        <title>Palmland Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="home__page">
        {/* <Banner /> */}
        <GoogleBanner onSubmit={handleChildSubmit} />

        <Properties
          loading={loading}
          properties={properties}
          sectionTitle="Featured Properties"
        />
        <Properties
          loading={loading}
          properties={properties}
          sectionTitle="Recent Properties"
        />
        <Properties
          loading={loading}
          properties={properties}
          sectionTitle="Upcoming Properties"
        />
         <Properties
          loading={loading}
          properties={properties}
          sectionTitle="Our Popular Homes"
        />
        <Agents />
      </div>
    </>
  );
}
