spring:
  profiles:
    active: dev
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: <apoorvaksingh2022@gmail.com>
    password: <vyrnqjxoagkymfcr>
    port: '587'
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  bucket:
    name: palmland
aws:
  cloud:
    credentials:
      access-key: 
      secret-key:
      url:
    region:
      static: eu-north-1
    stack:
      auto: false
upload:
  path: src/main/resources/images

